/**
 * Train a tiny graph-attention Q-policy on the GreenWave headless sim.
 * Independent Q-learning + behavioral cloning of advanced max-pressure.
 * Run: node_modules/.bin/esbuild scripts/trainCoord.ts --bundle --platform=node --format=esm --outfile=/tmp/trainCoord.mjs && node /tmp/trainCoord.mjs
 */
import { writeFileSync } from 'node:fs';
import { TrafficSim } from '../src/sim/engine';
import { MIN_GREEN, type ControlMode, type ScenarioId } from '../src/sim/types';
import { NODE_COUNT } from '../src/sim/network';
import { RNG } from '../src/sim/rng';
import {
  cloneWeights,
  forwardAll,
  initWeights,
  setActiveWeights,
  trainQStep,
  type IxView,
} from '../src/optimizer/coordPolicy';
import type { CoordEval, CoordWeights } from '../src/optimizer/coordWeights';

const DT = 0.25;
const HOLD_SEED = 9091;
const TRAIN_SECONDS = 48;

function snap(sim: TrafficSim): IxView[] {
  return sim.ix.map((x) => ({
    phase: x.phase,
    elapsed: x.elapsed,
    yellow: x.yellow,
    allRed: x.allRed,
    qN: x.qN,
    qE: x.qE,
    qS: x.qS,
    qW: x.qW,
    pN: x.pN,
    pE: x.pE,
    pS: x.pS,
    pW: x.pW,
  }));
}

function mpExpert(ix: IxView[], i: number): boolean {
  const x = ix[i];
  if (x.yellow || x.allRed || x.elapsed < MIN_GREEN) return false;
  const pNS = x.pN + x.pS;
  const pEW = x.pE + x.pW;
  const serving = x.phase === 0 ? pNS : pEW;
  const other = x.phase === 0 ? pEW : pNS;
  return other > serving + 2.2;
}

function runEval(mode: ControlMode, seed: number, seconds: number, scenario: ScenarioId = 'rush') {
  const sim = new TrafficSim(seed, true);
  sim.headless = true;
  sim.setScenario(scenario);
  sim.setMode(mode);
  sim.reset(seed);
  sim.setMode(mode);
  const steps = Math.ceil(seconds / DT);
  for (let i = 0; i < steps; i++) sim.step(DT);
  const m = sim.metrics();
  const fitness = m.throughput / (8 + m.avgWait) - m.stops * 0.15 - m.p95Wait * 0.02;
  return { ...m, fitness };
}

function writeWeights(w: CoordWeights) {
  const rnd = (arr: number[]) => arr.map((x) => Number(Number(x).toFixed(5)));
  const obj = {
    kind: w.kind,
    H: w.H,
    S: w.S,
    Ws: rnd(w.Ws),
    bs: rnd(w.bs),
    Wn: rnd(w.Wn),
    bn: rnd(w.bn),
    Wo: rnd(w.Wo),
    bo: rnd(w.bo),
    Wq: rnd(w.Wq),
    bq: rnd(w.bq),
    beta: w.beta,
    trained: w.trained,
    note: w.note,
    eval: w.eval,
  };
  const body = `/** Shipped graph-attention policy weights. Regenerated by scripts/trainCoord.ts. */
export type CoordKind = 'qattn' | 'graph-mp';

export interface CoordEval {
  fixedWait: number;
  adaptiveWait: number;
  coordWait: number;
  fixedThru: number;
  adaptiveThru: number;
  coordThru: number;
  seed: number;
}

export interface CoordWeights {
  kind: CoordKind;
  H: number;
  S: number;
  Ws: number[];
  bs: number[];
  Wn: number[];
  bn: number[];
  Wo: number[];
  bo: number[];
  Wq: number[];
  bq: number[];
  beta: number;
  trained: boolean;
  note: string;
  eval?: CoordEval;
}

export const COORD_WEIGHTS: CoordWeights = ${JSON.stringify(obj, null, 2)};
`;
  writeFileSync('/workspace/greenwave/src/optimizer/coordWeights.ts', body);
}

function collectBC(seed: number, scenario: ScenarioId, seconds: number) {
  const sim = new TrafficSim(seed, true);
  sim.headless = true;
  sim.setScenario(scenario);
  sim.setMode('adaptive');
  sim.reset(seed);
  sim.setMode('adaptive');
  const rows: { ix: IxView[]; i: number; a: number }[] = [];
  const steps = Math.ceil(seconds / DT);
  const every = Math.round(1 / DT);
  for (let s = 0; s < steps; s++) {
    sim.step(DT);
    if (s % every !== 0) continue;
    sim.updateQueues();
    const ix = snap(sim);
    for (let i = 0; i < NODE_COUNT; i++) {
      if (ix[i].yellow || ix[i].allRed) continue;
      rows.push({ ix, i, a: mpExpert(ix, i) ? 1 : 0 });
    }
  }
  return rows;
}

function main() {
  const t0 = Date.now();
  const rng = new RNG(2026);
  const w = initWeights(() => rng.next(), 0.22);
  w.bq[0] = 0.25;
  w.bq[1] = -0.15;

  console.log('BC: collecting advanced max-pressure demonstrations…');
  const scenarios: ScenarioId[] = ['rush', 'midday', 'afternoon', 'rush', 'midday', 'afternoon'];
  const bc: { ix: IxView[]; i: number; a: number }[] = [];
  scenarios.forEach((sc, k) => {
    const rows = collectBC(1700 + k * 17, sc, 36);
    bc.push(...rows);
    console.log(`  ${sc} seed ${1700 + k * 17}: ${rows.length} samples`);
  });

  const topology = new TrafficSim(1, true).net;
  console.log(`BC: ${bc.length} samples, training…`);
  for (let ep = 0; ep < 8; ep++) {
    let loss = 0;
    let n = 0;
    for (let k = 0; k < 400; k++) {
      const row = bc[rng.int(0, bc.length - 1)];
      const target = row.a === 1 ? [0.05, 0.95] : [0.95, 0.05];
      loss += trainQStep(w, topology, row.ix, row.i, target, 0.012);
      n++;
    }
    console.log(`  epoch ${ep + 1} mse ${(loss / n).toFixed(4)}`);
  }

  console.log('Q-learning fine-tune…');
  const qScenarios: ScenarioId[] = ['rush', 'midday', 'afternoon', 'rush', 'afternoon', 'midday'];
  for (let ep = 0; ep < 18; ep++) {
    const sc = qScenarios[ep % qScenarios.length];
    const seed = 3300 + ep * 41;
    const sim = new TrafficSim(seed, true);
    sim.headless = true;
    sim.setScenario(sc);
    sim.setMode('coord');
    sim.reset(seed);
    setActiveWeights(w);
    const eps = Math.max(0.05, 0.4 - ep * 0.018);
    let votes: boolean[] = new Array(NODE_COUNT).fill(false);
    let prevIx: IxView[] | null = null;
    let prevA: number[] | null = null;
    let prevCompleted = 0;
    let prevQueued = 0;
    sim.coordVoteHook = (i) => votes[i];
    sim.setMode('coord');

    const steps = Math.ceil(TRAIN_SECONDS / DT);
    const every = Math.round(1 / DT);
    let td = 0;
    let nTd = 0;
    for (let s = 0; s < steps; s++) {
      sim.step(DT);
      if (s % every !== 0) continue;
      sim.updateQueues();
      const ix = snap(sim);
      const cache = forwardAll(sim.net, ix, w);
      const m = sim.metrics();
      if (prevIx && prevA) {
        const r =
          -0.045 * (sim.queued - prevQueued) -
          0.012 * sim.queued -
          0.008 * m.avgWait +
          0.55 * (m.completed - prevCompleted);
        for (let k = 0; k < 8; k++) {
          const i = rng.int(0, NODE_COUNT - 1);
          if (prevIx[i].yellow || prevIx[i].allRed) continue;
          const qn = cache.Q[i];
          const a = prevA[i];
          const target = [qn[0], qn[1]];
          target[a] = r + 0.9 * Math.max(qn[0], qn[1]);
          td += trainQStep(w, sim.net, prevIx, i, target, 0.004);
          nTd++;
        }
      }
      prevIx = ix;
      prevA = cache.votes.map((v, i) => {
        if (ix[i].yellow || ix[i].allRed) return 0;
        if (rng.next() < eps) return rng.next() < 0.28 ? 1 : 0;
        return v ? 1 : 0;
      });
      votes = prevA.map((a) => a === 1);
      prevCompleted = m.completed;
      prevQueued = sim.queued;
    }
    const m = sim.metrics();
    console.log(
      `  ep ${ep + 1} ${sc} wait ${m.avgWait.toFixed(1)}s thru ${m.throughput.toFixed(0)} td ${
        nTd ? (td / nTd).toFixed(3) : '—'
      } eps ${eps.toFixed(2)}`,
    );
  }

  w.trained = true;
  w.kind = 'qattn';
  setActiveWeights(w);

  console.log('Held-out rush eval (seed %d, 70s)…', HOLD_SEED);
  const fixed = runEval('fixed', HOLD_SEED, 70, 'rush');
  const adaptive = runEval('adaptive', HOLD_SEED, 70, 'rush');

  setActiveWeights(w);
  w.kind = 'qattn';
  w.trained = true;
  const qattn = runEval('coord', HOLD_SEED, 70, 'rush');

  const graphW = cloneWeights(w);
  graphW.kind = 'graph-mp';
  graphW.trained = false;
  setActiveWeights(graphW);
  const graph = runEval('coord', HOLD_SEED, 70, 'rush');

  console.log(
    JSON.stringify(
      {
        fixed: { wait: fixed.avgWait, thru: fixed.throughput, fit: fixed.fitness },
        adaptive: { wait: adaptive.avgWait, thru: adaptive.throughput, fit: adaptive.fitness },
        qattn: { wait: qattn.avgWait, thru: qattn.throughput, fit: qattn.fitness },
        graphMp: { wait: graph.avgWait, thru: graph.throughput, fit: graph.fitness },
      },
      null,
      2,
    ),
  );

  const qattnBeatsMp = qattn.fitness > adaptive.fitness && qattn.avgWait <= adaptive.avgWait + 1.5;
  const ship: CoordWeights = qattnBeatsMp ? w : graphW;
  if (qattnBeatsMp) {
    ship.kind = 'qattn';
    ship.trained = true;
    ship.note =
      'Independent Q-learning + BC of advanced max-pressure. One graph-attention layer (H=24). Beats advanced MP on held-out rush.';
  } else {
    ship.kind = 'graph-mp';
    ship.trained = false;
    ship.note =
      'Q-learning did not beat advanced max-pressure on the held-out rush seed. Inference is graph-smoothed advanced max-pressure (attention over neighbor pressures, β=0.35). Network weights from BC+Q are stored but unused at runtime.';
  }
  const ev: CoordEval = {
    fixedWait: fixed.avgWait,
    adaptiveWait: adaptive.avgWait,
    coordWait: ship.kind === 'qattn' ? qattn.avgWait : graph.avgWait,
    fixedThru: fixed.throughput,
    adaptiveThru: adaptive.throughput,
    coordThru: ship.kind === 'qattn' ? qattn.throughput : graph.throughput,
    seed: HOLD_SEED,
  };
  ship.eval = ev;
  ship.beta = 0.35;
  writeWeights(ship);
  console.log(`Shipped kind=${ship.kind} in ${(Date.now() - t0) / 1000}s`);
  console.log(ship.note);
}

main();
